(module $env
	(func $opa_builtin0 (export "opa_builtin0") (import "host" "builtin0")
		(param $id i32) 
		(param $_ctx i32) 
		(result i32))
	(func $opa_builtin1  (export "opa_builtin1") (import "host" "builtin1")
		(param $id i32) 
		(param $_ctx i32) 
		(param $arg1 i32) 
		(result i32))
	(func $opa_builtin2 (export "opa_builtin2") (import "host" "builtin2") 
		(param $id i32) 
		(param $_ctx i32) 
		(param $arg1 i32) 
		(param $arg2 i32) 
		(result i32))
	(func $opa_builtin3 (export "opa_builtin3") (import "host" "builtin3")
		(param $id i32) 
		(param $_ctx i32) 
		(param $arg1 i32) 
		(param $arg2 i32) 
		(param $arg3 i32) 
		(result i32))
	(func $opa_builtin4 (export "opa_builtin4") (import "host" "builtin4")
		(param $id i32) 
		(param $_ctx i32) 
		(param $arg1 i32) 
		(param $arg2 i32) 
		(param $arg3 i32) 
		(param $arg4 i32) 
		(result i32))
	(func $opa_abort(export "opa_abort") (import "host" "builtin_abort") 
		(param $ptr i32))
	(func $opa_println (export "opa_println") (import "host" "builtin_println")
		(param $ptr i32))
	(memory (export "memory") 5 5))
